export const metadata = {
  title: "Terms of Service — Muvie",
};

export default function TermsPage() {
  return (
    <main style={{ maxWidth: 720, margin: "0 auto", padding: "48px 24px", fontFamily: "sans-serif", lineHeight: 1.7, color: "#ececec", background: "#121212", minHeight: "100vh" }}>
      <h1>Terms of Service</h1>
      <p><em>Last updated: March 2026</em></p>

      <h2>1. Acceptance of Terms</h2>
      <p>By using Muvie, you agree to these Terms of Service. If you do not agree, do not use the app.</p>

      <h2>2. Description of Service</h2>
      <p>Muvie is an AI-powered app that helps you discover movies and TV shows and decide what to watch. Recommendations are generated by an AI and may not always be accurate.</p>

      <h2>3. User Accounts</h2>
      <ul>
        <li>You must be at least 13 years old to create an account.</li>
        <li>You are responsible for maintaining the security of your device and passkey.</li>
        <li>You agree not to use Muvie for any unlawful purpose.</li>
      </ul>

      <h2>4. User Content</h2>
      <p>Messages you send to the AI assistant are used solely to generate responses. You retain ownership of your content. By using the service you grant us a limited license to process your messages to provide the service.</p>

      <h2>5. Prohibited Conduct</h2>
      <ul>
        <li>Do not attempt to reverse engineer, hack, or disrupt the service.</li>
        <li>Do not use automated scripts or bots to access the service.</li>
        <li>Do not submit content that is illegal, harmful, or violates others' rights.</li>
      </ul>

      <h2>6. Disclaimer of Warranties</h2>
      <p>Muvie is provided "as is" without warranties of any kind. AI recommendations are for entertainment purposes and we make no guarantees about their accuracy.</p>

      <h2>7. Limitation of Liability</h2>
      <p>To the maximum extent permitted by law, Muvie is not liable for any indirect, incidental, or consequential damages arising from your use of the service.</p>

      <h2>8. Changes to Terms</h2>
      <p>We may update these terms at any time. Continued use of the app after changes constitutes acceptance of the new terms.</p>

      <h2>9. Contact</h2>
      <p>For questions about these terms, contact us at: <a href="mailto:hi@muvie.org" style={{ color: "#6c63ff" }}>hi@muvie.org</a></p>
    </main>
  );
}
